# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e48fabbc9ba7796faf22fb75b81d25fb067523457c271a7d0dfa44962450f377653582e0de44ce7556586df55a286bb0e64a7f6f39b1b8f5c14abb5efa37c81f
  paypal_host: https://www.sandbox.paypal.com
  #app_host: http://192.168.1.5:3000
  app_host: http://38e193cd.ngrok.com 
  paypal_account: raymonmina-seller@gmail.com

test:
  secret_key_base: 221f9d4745e633acfdaad3d12238d5a0f4bf8b5c64f366ba4be025e168d9f9373fbec73840ed8ffb7d4bdcf46a6ac1ee32526a93766714334fa91abd536079a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
  #app_host: http://192.168.1.5:3000     #should be changed to websites name when deployed
  app_host: http://38e193cd.ngrok.com 
  paypal_account: raymonmina-seller@gmail.com